### ISSUE TITLE
State\Province is missing on the Address form cshtml

### ISSUE THREAD

**Issue by sitefinitysteve** [Ucommercenet/Ucommerce.Sitefinity.UI#73]
https://github.com/Ucommercenet/Ucommerce.Sitefinity.UI/blob/develop/Ucommerce.Sitefinity.UI/Mvc/Views/Address/Detail.Index.cshtml

**Comment by nebse** [comment]
Hello @sitefinitysteve — just a heads up that we have entered this request into our product management system.

Closing this issue for now.

Kind regards,
Esben
