### ISSUE TITLE
Cannot compile latest release (3.5.1)

### ISSUE THREAD

**Issue by vbishurov** [Ucommercenet/Ucommerce.Sitefinity.UI#88]
The build cannot complete due to the inability to restore NuGet packages. Packages with version 9.5.1.21260 are no longer published on NuGet. Error below:

Unable to find version '9.5.1.21260' of package 'Ucommerce.Sitefinity'.
      https://api.nuget.org/v3/index.json: Package 'Ucommerce.Sitefinity.9.5.1.21260' is not found on source 'https://api.nuget.org/v3/index.json'.
      https://nuget.sitefinity.com/nuget: Package 'Ucommerce.Sitefinity.9.5.1.21260' is not found on source 'https://nuget.sitefinity.com/nuget'.

To build it I had to update packages.config and references in .csproj file to use version 9.5.1.21265 instead.

**Comment by MadsMagnusDue** [comment]
Hey Velizar Bishurov 

Thanks for reporting this to us. 

Have you pulled the latest changes for this repository down? 

Because we have made a fix for this and merged it into the default branch: https://github.com/Ucommercenet/Ucommerce.Sitefinity.UI/pull/87

Regards
Mads

**Comment by vbishurov** [comment]
I was able to build it, yes. I needed the specific version for debugging purposes but thankfully the changes weren't significant.
